AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Exclude:
    - "lib/env_file_syrup/lines/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Enabled: false
